# Generated by Django 5.1.2 on 2024-10-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Reg_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Release_Year', models.DateField()),
                ('Duration', models.PositiveIntegerField()),
                ('Channel_Id', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_Id', models.IntegerField()),
                ('Subscription_Type', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Duration', models.PositiveIntegerField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('Rating', models.IntegerField()),
                ('Review_Date', models.DateTimeField(auto_now_add=True)),
                ('Movie_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.movie')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Profile_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Card_Number', models.CharField(max_length=16)),
                ('Expiration_Date', models.DateField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.user')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('Watch_list_Id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('Movie_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.movie')),
                ('Profile_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.profile')),
            ],
        ),
    ]
