# Generated by Django 5.1.2 on 2024-10-24 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_netflix', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('Channel_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Channel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Channel_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_netflix.channel'),
        ),
    ]
